import type { StringTables } from '@tzg/core';

/** Kiswahili wording has not yet been checked by a native speaker (KNOWN_ISSUES U3). */
export const poolStrings: StringTables = {
  sw: {
    'shell.rotate': 'Zungusha simu yako ilale ili ucheze',
    'pool.power': 'Nguvu',
    'pool.spin': 'Mzunguko',
    'howTo.title': 'Jinsi ya kucheza',
    'howTo.body': '• Buruta kidole mezani kulenga.\n• Vuta kipimo cha nguvu (kulia) chini, kisha achia kupiga.\n• Mzunguko: sogeza kitone kwenye mpira mweupe kabla ya kupiga.\n• Ukanda ulio chini ya meza: buruta kulenga kwa usahihi zaidi.',
    'howTo.ok': 'Sawa, tucheze',
    'pool.hint': 'Buruta mezani kulenga. Vuta kipimo cha nguvu chini kisha achia kupiga.',
    'pool.hintBallInHand': 'Buruta mpira mweupe kuuweka, kisha lenga na upige.',
    'pool.placeholder': 'MICHORO YA MUDA',
    'ui.back': 'Rudi',
    'pool.menu': 'Menyu',
    'menu.title': 'Bongo Pool Table',
    'menu.continue': 'Endelea na mchezo',
    'menu.play': 'Cheza',
    'menu.stats': 'Takwimu',
    'menu.rules': 'Sheria',
    'menu.settings': 'Mipangilio',
    'stats.title': 'Takwimu',
    'stats.vsComputer': 'Kompyuta ({level}): umeshinda {won} kati ya {played}',
    'stats.twoPlayers': 'Wachezaji wawili: michezo {n}',
    'rules.title': 'Sheria za Blackball',
    'rules.body': '• Kuna mipira 7 myekundu, 7 ya njano na mmoja mweusi. Ingiza mipira yako yote ya rangi yako, kisha mweusi ili ushinde.\n• Rangi ya kwanza unayoingiza peke yake, hata wakati wa kupasua, inakuwa yako.\n• Ukiingiza mpira wako, unaendelea kucheza. Usipoingiza, zamu inapita.\n• Faulo: kutogusa mpira, kugusa mpira usio sahihi kwanza, kuingiza mpira mweupe au wa mpinzani, au hakuna mpira unaofika ukingoni. Mpinzani anapata mpira mkononi popote.\n• Ukiingiza mweusi mapema au kwa faulo, unashindwa. Mweusi ukiingia wakati wa kupasua, mipira inapangwa upya.',
    'settings.title': 'Mipangilio',
    'settings.language': 'Lugha',
    'settings.sound': 'Sauti',
    'settings.on': 'Washa',
    'settings.off': 'Zima',
    'language.sw': 'Kiswahili',
    'language.en': 'English',
    'pool.newGame': 'Mchezo mpya',
    'pool.confirmNewGame': 'Gusa tena kuanza upya',
    'player.name': 'Mchezaji {n}',
    'player.computer': 'Kompyuta',
    'picker.title': 'Unacheza na nani?',
    'picker.twoPlayers': 'Wachezaji wawili (simu moja)',
    'picker.computer': 'Kompyuta: {level}',
    'level.easy': 'Rahisi',
    'level.medium': 'Wastani',
    'level.hard': 'Ngumu',
    'status.computer': '{player} inacheza…',
    'group.red': 'Nyekundu',
    'group.yellow': 'Njano',
    'status.break': '{player}: pasua',
    'status.turn': '{player}: zamu yako',
    'status.continue': '{player}: endelea',
    'status.ballInHand': '{player}: mpira mkononi',
    'status.groups': '{player} ni {group}',
    'status.rerack': 'Mweusi umeingia wakati wa kupasua. Tunapanga upya',
    'foul.no-contact': 'Faulo: hukugusa mpira wowote',
    'foul.wrong-ball-first': 'Faulo: umegusa mpira usio sahihi kwanza',
    'foul.cue-ball-potted': 'Faulo: mpira mweupe umeingia',
    'foul.opponent-ball-potted': 'Faulo: umeingiza mpira wa mpinzani',
    'foul.no-cushion': 'Faulo: hakuna mpira uliogusa ukingo',
    'foul.illegal-break': 'Faulo: upasuaji si halali',
    'over.title': '{player} ameshinda!',
    'over.black-potted': 'Ameingiza mpira mweusi',
    'over.black-potted-early': '{loser} aliingiza mweusi mapema',
    'over.black-potted-with-foul': '{loser} aliingiza mweusi kwa faulo',
  },
  en: {
    'shell.rotate': 'Turn your phone sideways to play',
    'pool.power': 'Power',
    'pool.spin': 'Spin',
    'howTo.title': 'How to play',
    'howTo.body': '• Drag on the table to aim.\n• Pull the power bar (right) down, then let go to shoot.\n• Spin: move the dot on the white ball before you shoot.\n• The strip under the table: drag it to fine-tune your aim.',
    'howTo.ok': "OK, let's play",
    'pool.hint': 'Drag on the table to aim. Pull the power bar down and let go to shoot.',
    'pool.hintBallInHand': 'Drag the cue ball to place it, then aim and shoot.',
    'pool.placeholder': 'PLACEHOLDER ART',
    'ui.back': 'Back',
    'pool.menu': 'Menu',
    'menu.title': 'Bongo Pool Table',
    'menu.continue': 'Continue game',
    'menu.play': 'Play',
    'menu.stats': 'Stats',
    'menu.rules': 'Rules',
    'menu.settings': 'Settings',
    'stats.title': 'Stats',
    'stats.vsComputer': 'Computer ({level}): won {won} of {played}',
    'stats.twoPlayers': 'Two players: {n} games',
    'rules.title': 'Blackball rules',
    'rules.body': '• 7 reds, 7 yellows and the black. Pot all the balls of your colour, then the black to win.\n• The first colour you pot on its own, on the break too, becomes yours.\n• Pot one of your balls and you play again. Otherwise the turn passes.\n• Foul: hitting no ball, hitting the wrong ball first, potting the cue ball or an opponent\'s ball, or no ball reaching a cushion. Your opponent gets ball in hand anywhere.\n• Pot the black too early or with a foul and you lose. Black potted on the break: the balls are racked again.',
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.sound': 'Sound',
    'settings.on': 'On',
    'settings.off': 'Off',
    'language.sw': 'Kiswahili',
    'language.en': 'English',
    'pool.newGame': 'New game',
    'pool.confirmNewGame': 'Tap again to restart',
    'player.name': 'Player {n}',
    'player.computer': 'Computer',
    'picker.title': 'Who are you playing?',
    'picker.twoPlayers': 'Two players (one phone)',
    'picker.computer': 'Computer: {level}',
    'level.easy': 'Easy',
    'level.medium': 'Medium',
    'level.hard': 'Hard',
    'status.computer': '{player} is playing…',
    'group.red': 'Reds',
    'group.yellow': 'Yellows',
    'status.break': '{player} to break',
    'status.turn': '{player} to play',
    'status.continue': '{player}: play again',
    'status.ballInHand': '{player}: ball in hand',
    'status.groups': '{player} is on {group}',
    'status.rerack': 'Black potted on the break. Re-racking',
    'foul.no-contact': 'Foul: no ball hit',
    'foul.wrong-ball-first': 'Foul: wrong ball hit first',
    'foul.cue-ball-potted': 'Foul: cue ball potted',
    'foul.opponent-ball-potted': "Foul: opponent's ball potted",
    'foul.no-cushion': 'Foul: no ball reached a cushion',
    'foul.illegal-break': 'Foul: illegal break',
    'over.title': '{player} wins!',
    'over.black-potted': 'Potted the black',
    'over.black-potted-early': '{loser} potted the black too early',
    'over.black-potted-with-foul': '{loser} potted the black with a foul',
  },
};
