import type { StringTables } from '@tzg/core';

/** Kiswahili wording has not yet been checked by a native speaker (KNOWN_ISSUES U3). */
export const poolStrings: StringTables = {
  sw: {
    'shell.rotate': 'Zungusha simu yako ilale ili ucheze',
    'pool.power': 'Nguvu',
    'pool.hint': 'Buruta mezani kulenga. Vuta kipimo cha nguvu chini kisha achia kupiga.',
    'pool.hintBallInHand': 'Buruta mpira mweupe kuuweka, kisha lenga na upige.',
    'pool.placeholder': 'MICHORO YA MUDA',
    'pool.newGame': 'Mchezo mpya',
    'pool.confirmNewGame': 'Gusa tena kuanza upya',
    'player.name': 'Mchezaji {n}',
    'group.red': 'Nyekundu',
    'group.yellow': 'Njano',
    'status.break': '{player}: pasua',
    'status.turn': '{player}: zamu yako',
    'status.continue': '{player}: endelea',
    'status.ballInHand': '{player}: mpira mkononi',
    'status.groups': '{player} ni {group}',
    'status.rerack': 'Mweusi umeingia wakati wa kupasua. Tunapanga upya',
    'foul.no-contact': 'Faulo: hukugusa mpira wowote',
    'foul.wrong-ball-first': 'Faulo: umegusa mpira usio sahihi kwanza',
    'foul.cue-ball-potted': 'Faulo: mpira mweupe umeingia',
    'foul.opponent-ball-potted': 'Faulo: umeingiza mpira wa mpinzani',
    'foul.no-cushion': 'Faulo: hakuna mpira uliogusa ukingo',
    'foul.illegal-break': 'Faulo: upasuaji si halali',
    'over.title': '{player} ameshinda!',
    'over.black-potted': 'Ameingiza mpira mweusi',
    'over.black-potted-early': '{loser} aliingiza mweusi mapema',
    'over.black-potted-with-foul': '{loser} aliingiza mweusi kwa faulo',
  },
  en: {
    'shell.rotate': 'Turn your phone sideways to play',
    'pool.power': 'Power',
    'pool.hint': 'Drag on the table to aim. Pull the power bar down and let go to shoot.',
    'pool.hintBallInHand': 'Drag the cue ball to place it, then aim and shoot.',
    'pool.placeholder': 'PLACEHOLDER ART',
    'pool.newGame': 'New game',
    'pool.confirmNewGame': 'Tap again to restart',
    'player.name': 'Player {n}',
    'group.red': 'Reds',
    'group.yellow': 'Yellows',
    'status.break': '{player} to break',
    'status.turn': '{player} to play',
    'status.continue': '{player}: play again',
    'status.ballInHand': '{player}: ball in hand',
    'status.groups': '{player} is on {group}',
    'status.rerack': 'Black potted on the break. Re-racking',
    'foul.no-contact': 'Foul: no ball hit',
    'foul.wrong-ball-first': 'Foul: wrong ball hit first',
    'foul.cue-ball-potted': 'Foul: cue ball potted',
    'foul.opponent-ball-potted': "Foul: opponent's ball potted",
    'foul.no-cushion': 'Foul: no ball reached a cushion',
    'foul.illegal-break': 'Foul: illegal break',
    'over.title': '{player} wins!',
    'over.black-potted': 'Potted the black',
    'over.black-potted-early': '{loser} potted the black too early',
    'over.black-potted-with-foul': '{loser} potted the black with a foul',
  },
};
